using System;

namespace Pfz.DynamicObjects.Internal
{
	/// <summary>
	/// This type is used by emitted code generated by StructuralCaster.GetStaticInterface.
	/// </summary>
	public abstract class BaseDuckForTypes:
		BaseDuck
	{
		/// <summary>
		/// Gets the Type to which the calls are redirected.
		/// </summary>
		public abstract Type Type { get; }

		/// <summary>
		/// Re-casts the Type this objects references.
		/// </summary>
		public override T DuckCast<T>(object securityToken)
		{
			if (securityToken != null)
				throw new ArgumentException("Interfaces redirecting to static members do not support security-tokens.");

			return DuckCaster.GetStaticInterface<T>(Type);
		}

		/// <summary>
		/// Re-casts the Type this objects references.
		/// </summary>
		public override T StructuralCast<T>(object securityToken)
		{
			if (securityToken != null)
				throw new ArgumentException("Interfaces redirecting to static members do not support security-tokens.");

			return StructuralCaster.GetStaticInterface<T>(Type);
		}
	}
}
