using System;

namespace Pfz.DynamicObjects
{
	/// <summary>
	/// Interface that must be implemented by objects that will respond to
	/// dynamic-delegates generated by DelegateImplementer.
	/// </summary>
	public interface IProxyDelegate
	{
		/// <summary>
		/// Method invoked when the delegate is invoked.
		/// </summary>
		object Invoke(object[] parameters);
	}
}
